---
title: "Group-Lab-2"
output: html_document
---

```{r setup, include=FALSE}
# Loading data sources

knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(raster)
library(rgdal)
# WAC, RAC, and OD data
odData = read.csv("data/wa_od_main_JT00_2015.csv.gz") %>% as_tibble()
wacData = read.csv("data/wac2015.csv") %>% as_tibble()
racData = read.csv("data/rac2015.csv") %>% as_tibble()
KCtract = read.csv("data/KC_Tracts.csv") %>% as_tibble()
#shapefile KC counties
KC_shape <- shapefile("data/shapefiles/king10ct.shp")
#Shapefile for KC blocks
KC_block <- shapefile("data/shapefiles/kc_block_10.shp")


```

```{r, include=FALSE}
# Part 2: Data Wrangling boogaloo

#TRACT LEVEL DATA---------------------------------------------------------------
# Converting GeoID columns to characters 
odData[, 1:2] <- sapply(odData[, 1:2], as.character)
wacData[1] <- sapply(wacData[,1], as.character)
racData[1] <- sapply(racData[,1], as.character)


#OD Aggregated by Tracts
ODAGtract=aggregate(. ~ odData$wTract + odData$hTract,data=odData[,c(3:12)],FUN=sum)
#Wac Aggregated by Tracts
WACAGtract=aggregate(. ~ wacData$wTract,data=wacData[,c(2:52)],FUN=sum)
#Rac Aggregated by Tracts
RACAGtract=aggregate(. ~ racData$hTract,data=racData[,c(2:42)],FUN=sum)

#Selecting out tracts of interest non spatially (King County Tracts) ------------
# Subsetting the census tract (that we'll use to merge rows togethers)
odData$wTract <- substr(odData$w_geocode, 6, 11)
odData$hTract <- substr(odData$h_geocode, 6, 11)
#Work area subset
wacData$wTract <- substr(wacData$w_geocode, 6, 11)
#Residential area Subset
racData$hTract <- substr(racData$h_geocode, 6, 11)

#finding tracts that are within King County from a file that only has KC tracts
KCtracts <- dplyr::select(KCtract, GEOID10)
KCtracts$GEOID10 <- substr(KCtracts$GEOID10, 6, 11)


#Selecting tracts where the work and home tracts are within King County for the OD data
KCodtract <- filter(ODAGtract, ODAGtract$`odData$wTract` %in% KCtracts$GEOID10 == TRUE,
                      ODAGtract$`odData$hTract` %in% KCtracts$GEOID10 == TRUE)
KCodtract <- mutate(KCodtract, GEOID10 = paste0('53033', KCodtract$`odData$hTract`))
#Selecting tracts in King County for aggregated WAC data
KCwactract <- filter(WACAGtract, WACAGtract$`wacData$wTract` %in% KCtracts$GEOID10 == TRUE) 
KCwactract <-  mutate(KCwactract, GEOID10 = paste0('53033', KCwactract$`wacData$wTract`))
#Selecting tracts in King County for aggregated RAC data
KCractract <- filter(RACAGtract, RACAGtract$`racData$hTract` %in% KCtracts$GEOID10 == TRUE)
KCractract <-  mutate(KCractract, GEOID10 = paste0('53033', KCractract$`racData$hTract`))

#Joining Data to tract level shapefiles -----------------------------------------

#Joining rac with the shapefile
KC_rac_with_shape <- merge(KC_shape, KCractract, by='GEOID10')
#Joining wac with the shapefile
KC_wac_with_shape <- merge(KC_shape, KCwactract, by='GEOID10')



#BLOCK LEVEL DATA---------------------------------------------------------------


#OD data by block in KC
ODblk <- filter(odData, odData$wTract %in% KCtracts$GEOID10 == TRUE,
                odData$hTract %in% KCtracts$GEOID10 == TRUE)
#Work area characteristics by block in KC
WACblk <- filter(wacData, wacData$wTract %in% KCtracts$GEOID10 == TRUE)
WACblk <- mutate(WACblk, GEOID10 = paste0('53033', WACblk$wTract))
#Residential area characteristics by block in KC
RACblk <- filter(racData, racData$hTract %in% KCtracts$GEOID10 == TRUE)
RACblk <- mutate(RACblk, GEOID10 = paste0('53033', RACblk$hTract))
#Join to block level shapefiles
WACblk_with_shape <- merge(KC_block, WACblk, by='GEOID10')
RACblk_with_shape <- merge(KC_block, RACblk, by='GEOID10')
```
